### ISSUE TITLE
Getting audio echo and noise on conference call 

### ISSUE THREAD

**Issue by MuahammdUmar** [ConnectyCube/connectycube-web-samples#134]
I am getting echo on speaker when I do conference call with my peers. I am building the application in ReactJS. Please if anyone has faced the issue, suggest the solution.

**Comment by DaveLomber** [comment]
Thanks for reaching out and letting us know about the echo issue you’re experiencing. Echo can sometimes occur in conference calls due to how the audio is captured or played back. Here are a few steps that might help resolve it:

1) Enable Audio Processing Features:
If you’re using the WebRTC getUserMedia API, you can add constraints like echoCancellation, noiseSuppression, and autoGainControl to the audio track. For example:


```
const constraints = {
  audio: {
    echoCancellation: true,
    noiseSuppression: true,
    autoGainControl: true
  },
  video: true
};
.getUserMedia(constraints)
  .then(stream => {
    // Use this stream for your call
  })
  .catch(error => {
    console.error('Error getting media: ', error);
  });
```

2. Encourage the Use of Headphones:
If possible, ask participants to use headphones instead of speakers. This helps prevent the microphone from picking up audio from the speakers.

3. Check for Multiple Audio Inputs:
Make sure users are not joining the same call from multiple devices in close proximity, as this can create feedback loops.

4. Browser Updates & Mic Permissions:
Ensure everyone’s browser is up-to-date and that their microphone permissions are correctly configured.

Please give these recommendations a try, and let us know if you continue to experience echo issues.
