### ISSUE TITLE
Nested screens to viewers while sharing screens & half document when a doc shared - in conference call

### ISSUE THREAD

**Issue by pradeepnama2009** [ConnectyCube/connectycube-web-samples#161]
We have implemented javascript SDK, during conference call when host shares screens it's not perfectly visible to viewers. And when we share a document (pdf) then it is half visible to viewers. I am attaching screenshots what happens.

![crop image ](https://user-images.githubusercontent.com/2689286/149886474-98048b05-6ce3-49b4-8fc1-e22ea25d7ad1.jpeg)
![Screenshot 1](https://user-images.githubusercontent.com/2689286/149886495-dc7df9b5-5846-470f-9d05-15de9b152ed7.png)
![Screenshot 3](https://user-images.githubusercontent.com/2689286/149886499-580fedef-cbdf-4f49-bb68-0532fcf1a78a.png)
![Screenshot 4](https://user-images.githubusercontent.com/2689286/149886507-0976bf8e-5d4f-4edc-9298-378cb7a5e91f.png)

**Comment by Avia-Code** [comment]
Hello @pradeepnama2009, we are in a hurry to share great news your problem fixed in new samples:
Angular Conference Call Code Sample - https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat-conf-angular
React Conference Call Code Sample  - https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat-conf-react
If you will have problems, please create new issue with names of code sample.
